apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: pizzas.container.training
spec:
  group: container.training
  scope: Namespaced
  names:
    plural: pizzas
    singular: pizza
    kind: Pizza
    shortNames:
    - piz
  versions:
  - name: v1alpha1
    served: true
    storage: true
    schema:
      openAPIV3Schema:
        type: object
        required: [ spec ]
        properties:
          spec:
            type: object
            required: [ sauce, toppings ]
            properties:
              sauce:
                type: string
              toppings:
                type: array
                items:
                  type: string
    additionalPrinterColumns:
    - jsonPath: .spec.sauce
      name: Sauce
      type: string
    - jsonPath: .spec.toppings
      name: Toppings
      type: string
